### ISSUE TITLE
Copying a tar with an ImageIndex crashes

### ISSUE THREAD

**Issue by DennisDenuto** [carvel-dev/imgpkg#125]
**What steps did you take:**
1. Create a tarfile with an imageindex named `tar-with-image-index.tar`
2. imgpkg copy --tar ./tar-with-image-index.tar --to-repo some/repo
```
copy | importing 5 images...
copy | importing registry.local:5000/opinions/samples/opinion-server@sha256:e5892efcc2ffa9ca3ab27966300f66b63ba481e186487adfa71c5b9d425e20a8 -> index.docker.io/k8slt/testopinion@sha256:e5892efcc2ffa9ca3ab27966300f66b63ba481e186487adfa71c5b9d425e20a8...
copy | importing registry.local:5000/opinions/samples/spring-opinion-server@sha256:8d306713e8c3450e90468b5c148e6ebca1397d360e5b1ed7bb57bed6dc8e89cb -> index.docker.io/k8slt/testopinion@sha256:8d306713e8c3450e90468b5c148e6ebca1397d360e5b1ed7bb57bed6dc8e89cb...
copy | importing gcr.io/kubebuilder/kube-rbac-proxy@sha256:a06e7b56c5e1e63b87abb417344f59bf4a8e53695b8463121537c3854c5fda82 -> index.docker.io/k8slt/testopinion@sha256:a06e7b56c5e1e63b87abb417344f59bf4a8e53695b8463121537c3854c5fda82...
copy | importing registry.local:5000/opinions/manager@sha256:19a01b75cf512ceb70420243ea77d85e02e0ab1f9b814bec8dabe0153d3bd71a -> index.docker.io/k8slt/testopinion@sha256:19a01b75cf512ceb70420243ea77d85e02e0ab1f9b814bec8dabe0153d3bd71a...
copy | importing registry.local:5000/opinions/bundle@sha256:854c0f7ad5516b84faeff12c72946fbf8a1b3db54e1cd36f70de976540d3c633 -> index.docker.io/k8slt/testopinion@sha256:854c0f7ad5516b84faeff12c72946fbf8a1b3db54e1cd36f70de976540d3c633...
copy | imported 5 images
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14114a3]

goroutine 1 [running]:
github.com/k14s/imgpkg/pkg/imgpkg/cmd.processedImagesMediaType(0xc000098480, 0x7ffeefbff984, 0x1c, 0x0)
	github.com/k14s/imgpkg/pkg/imgpkg/cmd/copy.go:245 +0xe3
github.com/k14s/imgpkg/pkg/imgpkg/cmd.(*CopyOptions).Run(0xc0001a4000, 0x0, 0x0)
	github.com/k14s/imgpkg/pkg/imgpkg/cmd/copy.go:104 +0x573
github.com/k14s/imgpkg/pkg/imgpkg/cmd.NewCopyCmd.func1(0xc00013d600, 0xc00010ef00, 0x0, 0x4, 0x0, 0x0)
	github.com/k14s/imgpkg/pkg/imgpkg/cmd/copy.go:41 +0x2a
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00013d600, 0xc00010ef00, 0x0, 0x4, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xb2
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00013d600, 0xc00010ef00, 0x0, 0x4, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xb2
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc00013d600, 0xc00010ef00, 0x0, 0x4, 0x0, 0x0)
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0xb2
github.com/spf13/cobra.(*Command).execute(0xc00013d600, 0xc00010eec0, 0x4, 0x4, 0xc00013d600, 0xc00010eec0)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013cb00, 0xc00013cb00, 0xc00010eb80, 0xc000052748)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	github.com/k14s/imgpkg/cmd/imgpkg/imgpkg.go:30 +0x188
```

**What happened:**
imgpkg crashed

**What did you expect:**
copy command to succeed

**Anything else you would like to add:**
https://github.com/vmware-tanzu/carvel-imgpkg/blob/274d5a2cfc9518d2a453290035c43b752d2f490d/pkg/imgpkg/cmd/copy.go#L245
image.Image might be null if there is an ImageIndex instead.

**Environment:**

- imgpkg version (use `imgpkg --version`): v0.6.0
- Docker registry used (e.g. `Docker HUB`): dockerhub
- OS (e.g. from `/etc/os-release`): osx

**Comment by DennisDenuto** [comment]
Fixed as part of https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.6.1
